version: '3'
services:
  connector-cisa-known-exploited-vulnerabilities:
    image: THREATLENS/connector-cisa-known-exploited-vulnerabilities:6.4.8
    environment:
      - THREATLENS_URL=http://localhost
      - THREATLENS_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - "CONNECTOR_NAME=CISA Known Exploited Vulnerabilities"
      - CONNECTOR_SCOPE=cisa
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_DURATION_PERIOD=P2D
      - CISA_CATALOG_URL=https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json
      - CISA_CREATE_INFRASTRUCTURES=false
      - CISA_TLP=TLP:CLEAR
    restart: always
