version: '3'
services:
  connector-export-file-csv:
    image: THREATLENS/connector-export-file-csv:6.4.8
    environment:
      - THREATLENS_URL=http://localhost
      - THREATLENS_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=error
      - "EXPORT_FILE_CSV_DELIMITER=;"
    restart: always
