version: '3'
services:
  connector-export-ttps-file-navigator:
    image: THREATLENS/connector-export-ttps-file-navigator:6.4.8
    environment:
      - THREATLENS_URL=http://localhost
      - THREATLENS_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_NAME=ExportTTPsFileNavigator
      - CONNECTOR_SCOPE=application/vnd.mitre.navigator+json
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=error
    restart: always
