version: '3'
services:
  connector-export-file-stix:
    image: THREATLENS/connector-export-file-stix:6.4.8
    environment:
      - THREATLENS_URL=http://localhost
      - THREATLENS_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/vnd.oasis.stix+json
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=error
    restart: always
