version: '3'
services:
  connector-chapsvision:
    image: THREATLENS/connector-chapsvision:6.4.8
    environment:
      - THREATLENS_URL=http://localhost
      - THREATLENS_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_NAME=Chapsvision
      - CONNECTOR_SCOPE=chapsvision
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=error
      - CHAPSVISION_CERTIFICATE=Certificate_base64
      - CHAPSVISION_KEY=Key_base64
      - CHAPSVISION_QUERY_PARAMETER=_params
      - CHAPSVISION_START_DATE=2022-01-01
      - CHAPSVISION_INTERVAL=5 # In minutes
    restart: always
